version: '3'
services:
  typescript-express-app:
    build:
      context: ./task-api
    container_name: task-api
    ports: 
      - 5000:5000
    volumes:
      - ./task-api/src:/usr/app/src
        
  react-ui:
    build:
      context: ./task-ui
    ports:
      - "3000:3000"
    container_name: task-ui
    stdin_open: true
    volumes:
       - ./task-ui:/usr/src/app/task-ui
       - /usr/src/app/task-ui/node_modules
