version: '3'
services:
  typescript-express-app:
    build:
      context: ./task-api
    container_name: task-api
    environment:
      - PORT=${SERVER_PORT}
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./task-api/src:/usr/app/src
        
  react-ui:
    build:
      context: ./task-ui
    ports: 
      - ${UI_PORT}:${UI_PORT}
    environment:
      - PORT=${UI_PORT}
      - REACT_APP_SERVER_PORT=${SERVER_PORT}
    container_name: task-ui
    stdin_open: true
    volumes:
       - ./task-ui:/usr/src/app/task-ui
       - /usr/src/app/task-ui/node_modules
